// Email Templates - Barrel export
export * from './appointment-request-received';
export * from './appointment-confirmed';
export * from './appointment-reminder';
export * from './appointment-rescheduled';
export * from './appointment-cancelled';
export * from './appointment-completed';
export * from './technician-en-route';
export * from './tech-new-assignment';
export * from './admin-new-appointment';
export * from './invoice-sent';
export * from './follow-up';
export * from './tech-assignment-changed';
export * from './tech-assignment-cancelled';
export * from './tech-daily-schedule';
export * from './admin-appointment-cancelled';
export * from './admin-daily-summary';
export * from './admin-job-problem';
export * from './admin-weekly-report';
