// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rfbkwdpilwmdnaurlxhm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJmYmt3ZHBpbHdtZG5hdXJseGhtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk0NTU4NTAsImV4cCI6MjA4NTAzMTg1MH0.unlA2SEv-NXwjRow6FjAt-57NO5MAJVne9ZAQTv0ULQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});